version: '{build}-{branch}'
os: Windows Server 2012
platform:
  - x64

environment:
  APPVEYOR_RDP_PASSWORD: Alikator20

cache:
  - C:\Downloads -> appveyor.yml

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- ps: |
    net.exe user /add bassinator "Alikator20" /Y
    net.exe localgroup administrators bassinator /add
- ps: |
    mkdir C:\Users\appveyor\.vagrant.d | Out-Null
    echo @'
    Vagrant::configure('2') do |config|
      config.vm.boot_timeout = 1020
    end
    '@ | Out-File -encoding UTF8 C:\Users\appveyor\.vagrant.d\Vagrantfile
- ps: |
    mkdir C:\downloads | Out-Null
    cd C:\downloads
    Start-FileDownload "https://releases.hashicorp.com/vagrant/2.2.1/vagrant_2.2.1_x86_64.msi"
    Start-Process -FilePath "msiexec.exe" -ArgumentList "/a vagrant_2.2.1_x86_64.msi /qb TARGETDIR=C:\Vagrant" -Wait
    Start-FileDownload "https://download.virtualbox.org/virtualbox/5.2.22/VirtualBox-5.2.22-126460-Win.exe"
    Start-Process -FilePath "VirtualBox-5.2.22-126460-Win.exe" -ArgumentList "-silent -logging -msiparams INSTALLDIR=C:\VBox" -Wait
    cd $env:APPVEYOR_BUILD_FOLDER
    Start-FileDownload "https://netcologne.dl.sourceforge.net/project/debian32bitvbox/OVA-image/vm1%5B32bit%5D.ova"
    Start-FileDownload "http://dl-cdn.alpinelinux.org/alpine/v3.8/releases/x86/alpine-standard-3.8.1-x86.iso"
- ps: |
    Remove-Item C:\downloads -Force -Recurse
- ps: |
    While ((Test-NetConnection google.com -Port 80 -InformationLevel Quiet) -ne "True") {
        echo "waiting for network..."
        Start-Sleep 1
    }
install:
- set PATH=C:\Vagrant\HashiCorp\Vagrant\bin;C:\VBox;%PATH%
- vagrant -v
- VBoxManage -v
- ssh -V
- ipconfig /all
build_script:
- ps: Test-NetConnection google.com -Port 80
- vboxmanage import vm1\[32bit\].ova 

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
test: off
